### PR TITLE
Hide SlideOutView when Row is not open

### PR DESCRIPTION
**Pull request by lkalashov**

### CODE REVIEW

**Comment by esthor** [comment]
Hi @lkalashov and thanks for the PR! Could you explain what issue this is solving for you? Is it platform specific (android, ios, web, etc.)?

**Comment by lkalashov** [comment]
Hi! The problem is that when row is partially opaque, quickActions are visible through it. 
Maybe there is a way to handle this?

**Comment by esthor** [comment]
@lkalashov Did you find a way?

**Comment by lkalashov** [comment]
Unfortunately no. There were some more problems, so decided to proceed making changes in own fork.

**Comment by esthor** [comment]
Happy to work with you on it if you'd like. I may have some time later today or this week. If I understand correctly, the main issue is that you want to have some transparency in the row, but that leads to the quick actions being visible underneath?

**Pull request closed without merging**
